#! /usr/bin/env bash
set -e

# Install dependencies
# yarn

# Publish `production` release
# expo publish --release-channel production --non-interactive

#### 2. Building iOS Standalone App ####
# Start building standalone ios build using `production` release channel
# expo build:ios --release-channel production --non-interactive --no-publish

# Download the artifact to current directory as `app.ipa`
# curl -o app.ipa "$(expo url:ipa --non-interactive)"

# credentials
export DELIVER_USERNAME=$EXPO_APPLE_ID
export DELIVER_PASSWORD=$EXPO_APPLE_ID_PASSWORD

# Use fastlane to upload your current standalone iOS build to test flight 
# on iTunes Connect.
# fastlane deliver --verbose --ipa "app.ipa" --skip_screenshots --skip_metadata



#### 3. Building Android Standalone App ####
# Start building standalone android build using `production` release channel
# expo build:android --release-channel production --non-interactive --no-publish

# Download the built android binary
# curl -o app.apk "$(expo url:apk --non-interactive)"

# Use fastlane to upload your current standalone android build
# Customize this to fit your needs. Take note of env variables. 
# Check out https://docs.fastlane.tools for more info.
# fastlane supply --track 'production' \
#   --json_key '<path/to/json_key.json>' \
#   --package_name "<your-package-name>" \
#   --apk "app.apk" --skip_upload_metadata \
#   --skip_upload_images --skip_upload_screenshots

